# Generated by Django 5.1.6 on 2025-02-18 13:52

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="author",
            fields=[
                ("author_id", models.AutoField(primary_key=True, serialize=False)),
                ("author_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="cart",
            fields=[
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="genre",
            fields=[
                ("genre_id", models.AutoField(primary_key=True, serialize=False)),
                ("genre_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="orders",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="publisher",
            fields=[
                ("publisher_id", models.AutoField(primary_key=True, serialize=False)),
                ("publisher_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=20)),
                (
                    "contact_number",
                    models.CharField(default="0000000000", max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("book_name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "author_id",
                    models.ForeignKey(
                        db_column="author_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="api.author",
                    ),
                ),
                (
                    "genre_id",
                    models.ForeignKey(
                        db_column="genre_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="api.genre",
                    ),
                ),
                (
                    "publisher_id",
                    models.ForeignKey(
                        db_column="publisher_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="api.publisher",
                    ),
                ),
                (
                    "seller_name",
                    models.ForeignKey(
                        db_column="seller_name",
                        default=api.models.get_default_seller,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cart_items",
            fields=[
                ("cart_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "book_id",
                    models.ForeignKey(
                        db_column="book_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="api.book",
                    ),
                ),
                (
                    "cart_id",
                    models.ForeignKey(
                        db_column="cart_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="api.cart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order_items",
            fields=[
                ("order_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "book_id",
                    models.ForeignKey(
                        db_column="book_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="api.book",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        db_column="order_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="api.orders",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orders",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="api.user",
            ),
        ),
    ]
