# Generated by Django 5.1.6 on 2025-02-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_user_delete_usersubmision_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
