# Generated by Django 5.1.6 on 2025-02-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
