# Generated by Django 5.1.6 on 2025-02-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_bookdetails_id_alter_bookdetails_book_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.bookdetails",
            ),
        ),
    ]
