# Generated by Django 5.1.6 on 2025-02-17 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_order_price_remove_order_product_order_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookdetails",
            name="seller",
            field=models.ForeignKey(
                db_column="seller",
                default="user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="api.user",
            ),
        ),
    ]
