# Generated by Django 5.1.6 on 2025-02-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_bookdetails_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetails",
            name="seller",
            field=models.ForeignKey(
                db_column="seller",
                default="hemanth",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="api.user",
            ),
        ),
    ]
