# Generated by Django 5.1.6 on 2025-02-17 14:02

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_bookdetails_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetails",
            name="seller",
            field=models.ForeignKey(
                db_column="seller",
                default=api.models.get_default_seller,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="api.user",
            ),
        ),
    ]
