# Generated by Django 5.1.6 on 2025-02-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_bookdetails_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="book",
        ),
        migrations.DeleteModel(
            name="BookDetails",
        ),
    ]
