# Generated by Django 5.1.6 on 2025-02-17 14:12

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_order_book_delete_bookdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookDetails",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("publisher", models.CharField(max_length=255)),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "seller",
                    models.ForeignKey(
                        db_column="seller",
                        default=api.models.get_default_seller,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.bookdetails",
            ),
        ),
    ]
