# Generated by Django 5.1.6 on 2025-02-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_bookdetails_order_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookdetails",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="order_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
