# Generated by Django 5.1.6 on 2025-02-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_bookdetails_quantity_order_order_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetails",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
