"""corrected cascade

Revision ID: 5189d9273651
Revises: 62ea447b8b92
Create Date: 2025-03-03 17:34:20.310860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5189d9273651'
down_revision: Union[str, None] = '62ea447b8b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_publisher_publisher_id', table_name='publisher')
    op.drop_table('publisher')
    op.drop_index('ix_order_items_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_author_author_id', table_name='author')
    op.drop_table('author')
    op.drop_index('ix_books_book_id', table_name='books')
    op.drop_table('books')
    op.drop_index('ix_genre_genre_id', table_name='genre')
    op.drop_table('genre')
    op.drop_index('ix_orders_order_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_cart_cart_id', table_name='cart')
    op.drop_table('cart')
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_cart_items_id', table_name='cart_items')
    op.drop_table('cart_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cart_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_items_id', 'cart_items', ['id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('contact_number', sa.VARCHAR(), nullable=True),
    sa.Column('profile_image', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    op.create_table('cart',
    sa.Column('cart_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cart_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_cart_cart_id', 'cart', ['cart_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('order_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index('ix_orders_order_id', 'orders', ['order_id'], unique=False)
    op.create_table('genre',
    sa.Column('genre_id', sa.INTEGER(), nullable=False),
    sa.Column('genre_name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_index('ix_genre_genre_id', 'genre', ['genre_id'], unique=False)
    op.create_table('books',
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('book_name', sa.VARCHAR(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('genre_id', sa.INTEGER(), nullable=True),
    sa.Column('publisher_id', sa.INTEGER(), nullable=True),
    sa.Column('picture', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publisher_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index('ix_books_book_id', 'books', ['book_id'], unique=False)
    op.create_table('author',
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('author_name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index('ix_author_author_id', 'author', ['author_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_id', 'order_items', ['id'], unique=False)
    op.create_table('publisher',
    sa.Column('publisher_id', sa.INTEGER(), nullable=False),
    sa.Column('publisher_name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('publisher_id')
    )
    op.create_index('ix_publisher_publisher_id', 'publisher', ['publisher_id'], unique=False)
    # ### end Alembic commands ###
