"""Changed seller_name to seller_id in books

Revision ID: 69f6f66ac9ac
Revises: ccd3fc3e9493
Create Date: 2025-02-28 06:25:20.188748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f6f66ac9ac'
down_revision: Union[str, None] = 'ccd3fc3e9493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
